### ISSUE TITLE
i have a problem about this interface

### ISSUE THREAD

**Issue by gaoliang00001** [korvin011/ADS-Matlab-Interface#1]
Hello,Mr.Oleg [Iupikov]
   I have a problem. I can use this interface on some computers, but I found a problem when I used it on others computers. When using the  Runsimulation()  function, an error will be generated. The mistake is:
                `can not Run simulation.The exit code is 1`
   What I understand is that when calling the RunProcessAsync() function, there is a child process that has not ended, so the  exit value is 1. This error causes this interface to not be widely used. I want to ask you how to solve this mistake.
   Thank you very much!

**Comment by korvin011** [comment]
Hi. 
You may try to run ADS solver with the argument `Verbosity`, like this: 
`ADS.RunSimulation('Verbosity','all')` 
or 
`ADS.RunSimulation('Verbosity','none')`. 
This will disable parsing the ADS output by using `RunProcessAsync`, and ADS executable will be run by MATLAB's function `system` instead.

**Comment by gaoliang00001** [comment]
Hi.
 First,thank you for your reply.I have tried `Verbosity`. But there are still problems. The problems are as follows:


`***** Warning: Unable to locate environment value for AEL_PATH ***** 
 Using default value of "." 
 
***** Warning: Unable to locate environment value for HPEESOFSIM_AEL ***** 
 Using default value of "hpeesofsim" 
WARNING    AEL0056 hpeesofsim: AEL file not found 
*** FATAL ERROR: Unable to load default AEL personality *** 
Error use TADSInterface/RunSimulation (line 2065)
Cannot run simulation "hpeesofsim "netlist.log"". The system message is:
Qt: Untested Windows version 10.0 detected!

hpeesofsim (*) 450.shp Jan 21 2016, MINT version 4
    (64-bit windows built: 01/21/16 15:34:19)
Copyright 1995 - 2015 Keysight Technologies, 1989-2016.


***** Warning: Unable to locate environment value for AEL_PATH *****
 Using default value of "."

***** Warning: Unable to locate environment value for HPEESOFSIM_AEL *****
 Using default value of "hpeesofsim"
WARNING    AEL0056 hpeesofsim: AEL file not found
*** FATAL ERROR: Unable to load default AEL personality ***


Error simulation (line 17)
ADS.RunSimulation('Verbosity','all')`


I would like to ask you how to solve this problem. Thank you again for your reply,

Thanks
Gao

**Comment by korvin011** [comment]
It seems like environmental variables are not set. Have you set them as it is said in the 1st demo?
"
Set up environmental variables required for running ADS executables from command line. SetADSPaths **must be called at least once for each Matlab session**.
```
ADSInstallationDir = 'C:\ADS2019_Update1';
ADS.SetADSPaths(ADSInstallationDir);
```
"
Alternatively, set all required PATHs and env. variables manually in Windows and restart Matlab so it sees changes. You can find their list in the comment to method `GetPathStrings` or ADS documentation.

**Comment by gaoliang00001** [comment]
Thank you for your reply! 
I have been looking for information about ads interface recently. I am very happy to get your help. Thank you for your efforts. Can we realize the simulation control of ADS layout? Because I try to use ads for IC design, I want to ask whether to use this interface to control the layout simulation?


GAO
| |
高国梁
|
|
ggl960212@163.com
|
签名由网易邮箱大师定制
On 7/5/2020 18:25，Oleg Iupikov<notifications@github.com> wrote：

It seems like environmental variables are not set. Have you set them as it is said in the 1st demo?
"
Set up environmental variables required for running ADS executables from command line. SetADSPaths must be called at least once for each Matlab session.

ADSInstallationDir = 'C:\ADS2019_Update1';
ADS.SetADSPaths(ADSInstallationDir);


"
Alternatively, set all required PATHs and env. variables manually in Windows and restart Matlab so it sees changes. You can find their list in the comment to method GetPathStrings or ADS documentation.

**Comment by korvin011** [comment]
I have not had a need for that, therefore it was not implemented. So, if your solver is not in "hpeesofsim", then the answer is "no".
