### ISSUE TITLE
Unable to access the library "XXX"

### ISSUE THREAD

**Issue by yangkang1122** [korvin011/ADS-Matlab-Interface#17]
Hello！

       It's a pleasure to communicate with you.
       I have a problem for this interface.
       I created an ADS project and the project needs a library, so I added a library in the ADS UI. 
       In the end, I successfully simulated the project and got the result.

      But when I try to use this interface to simulate the project, I get an error:
      "Unable to access the library "XXX""
      I don't know why.

      And still the same problem occurs when I try to simulate the project using the command line:
      hpeesofsim.exe D:\Desktop\ADS demo\...\netlist.log

       How can I solve this problem ? Thank you very much.

**Comment by yangkang1122** [comment]
I solved this problem.
Set the environment variables of PC, refer to the URL:
https://edadocs.software.keysight.com/eesofkcads/ads-command-line-simulation-on-64-bit-windows-654133585.html
(see Issue #12)
In addition, you need to set the environment variable "COMPL_DIR=%HPEESOF_DIR%"

**Comment by korvin011** [comment]
Hi yangkang1122,

Thank you for posting the solution. It may be useful for others.

Once I had an issue with an external library used in one of the projects, and what helped to me is simply open the project in ADS IDE, and keep it open while running MATLAB scripts.
