### ISSUE TITLE
Running ADS from Matlab Error

### ISSUE THREAD

**Issue by sagar378** [korvin011/ADS-Matlab-Interface#2]
Hey,
Thanks for the ADS-Matlab interface you developed. That's amazing.
I was facing a problem running 'Demo020L__ChangeParameter_and_RunSimulation' showing error

"[ADS][09:12:43] Running ADS simulator "hpeesofsim"...
Error using TADSInterface/RunSimulation (line 2072)
Cannot run simulation. The exit code is 1"

Any idea why? Much appreciated your help.

Best Regards
Sagar

**Comment by korvin011** [comment]
Hey,
It may happen if the ADS executable "hpeesofsim" is not in the PATH.
Try to execute in Matlab `system('hpeesofsim.exe')`. If you get error "_'hpeesofsim.exe' is not recognized as an internal or external command..._", this is the case. Have you added the ADS executables to PATH in the current Matlab session as it is shown in 1st demo?
```
ADSInstallationDir = 'C:\ADS2019_Update1';
ADS.SetADSPaths(ADSInstallationDir);
```

**Comment by sagar378** [comment]
Hi, thanks for your response. Actually, it was with the license issue I figured out later. Running now... thanks again.
