### ISSUE TITLE
A problem of dsdump

### ISSUE THREAD

**Issue by YZCH1649801486** [korvin011/ADS-Matlab-Interface#20]
When I use the method "ReadDataset(DatasetFile)" of the TADSInterface, I encountered a problem as follows: 

Cannot dump the dataset file "E:\Java\UpperComputer\Java-Matlab-ADSCoSimulation\ADSProject\ACSimulation\data\ACSimulation.ds" using "dsdump".
The system message is:
"'dsdump' is not an internal or external command, nor is it a runnable program or batch file."

**Comment by DPDenjoyer** [comment]
Hi!

I encountered the same problem as you described. Since you marked this issue as solved, could you please explain to me or redirect me to a solution?

Thank you very much for your help!
