### ISSUE TITLE
Method 'PrintHeader' is not defined

### ISSUE THREAD

**Issue by seackone** [korvin011/ADS-Matlab-Interface#22]
Greetings to Chalmers!

Im running your examples. Number one works, number two always generates errors.

[ADS][18:21:19] All required environmental variables and paths are set and checked.
[ADS][18:21:19] The parameter "R" of the component "R:Rload" has been changed
[ADS][18:21:19]   at the netlist line 29:
[ADS][18:21:19]     R:Rload  Vout 0 R=1 Ohm Noise=yes
[ADS][18:21:19]     ↧↧↧ has changed to ↧↧↧
[ADS][18:21:19]     R:Rload  Vout 0 R=0.2 Ohm Noise=yes
[ADS][18:21:19] 

**Error using TADSInterface/PrintHeader
Method 'PrintHeader' is not defined for class 'TADSInterface' or is removed from MATLAB's search path.
Error in TADSInterface/RunSimulation (line 2062)
            this.PrintHeader();
Error in testscript (line 28)
    ADS.RunSimulation();**

Do you have any idea how to solve the problem? Executing "methods TADSInterface" doesnt show PrintHeader.

**Comment by korvin011** [comment]
Hi. This may happen if TADSInterface goes out of Matlab path (and current directory is indeed changing before starting simulation). Try `addpath('full_path_to_TADSInterface')` before executing the examples.

**Comment by seackone** [comment]
Thank you very much Oleg, that helped!

**Comment by seackone** [comment]
Thank you very much Oleg, that helped!
