### ISSUE TITLE
Private methods not defined

### ISSUE THREAD

**Issue by tsmoffat** [korvin011/ADS-Matlab-Interface#3]
Hi, many thanks for this tool, it looks amazing. I'm having an issue with Demo 2 when running RunSimulation MATLAB kicks out an error about (so far) PrintHeader, fprintf and RunProcessAsync not being defined for the TADSInterface class or being removed from MATLAB's search path. This is using R2020a, and I'm not entirely sure what the root cause is here.

Many thanks!

Tom

**Comment by korvin011** [comment]
Hi,

Just checked it, and confirm that it happens with Matlab R2020a. However, in Matlab R2017b it works without issues. After further investigation I found out that after changing the current path in the line `cd(NetlistPath);` in `RunSimulation` method, the interface object `this` looses access to own private and get-set- methods (so far).

As a work around, just add path with the `TADSInterface` to the Matlab search path, e.g. by executing `addpath('C:\PathToInterface')`.

**Comment by tsmoffat** [comment]
That has fixed it for now, thank you
