### ISSUE TITLE
Hi,i want to have a new need

### ISSUE THREAD

**Issue by gaoliang00001** [korvin011/ADS-Matlab-Interface#4]
Hi, many thanks for this tool, it looks amazing.I have some new need for this tool.  Based on this interface,can you control ADS optimization tool  through matlab? Can you further extend this interface? or give me some advice to control ADS optimization toolbox through matlab?thank you!

**Comment by korvin011** [comment]
Hi. Unfortunately, I haven't studied how to control ADS optimizer, and I have no time for such a major update. As an alternative, you can use Matlab-based optimizers (e.g. fminsearch) and use ADS just as solver.

**Comment by gaoliang00001** [comment]
I have read netlist.log txt. If i add a optimizaiton tool to schematic,  I found that netlist have some information about optimization. So can we control optimization by netlist like simulation function? Do you have some ideas about it?

**Comment by korvin011** [comment]
If the optimizer is controlled by the netlist, you can try to modify the optimizer's parameters using ChangeComponentParameter, or (more general) NetlistRegExpReplace methods.

**Comment by gaoliang00001** [comment]
But simulation and optimization are two kinds of controllers. How can I control the execution of optimization tool rather than simulation, because the netlist file contains two kinds of information.

**Comment by korvin011** [comment]
As I said, I haven't studied how the ADS optimizer works at low level. I can ASSUME it work similar to the parametric sweep controller, in which you specify the target solver. If so, the work with optimizer is similar to parametric sweeps, see 2nd demo.

**Comment by gaoliang00001** [comment]
Thank you ! I will try it!
