### ISSUE TITLE
Cannot run simulation: HPEESOF_DIR is set to an invalid directory

### ISSUE THREAD

**Issue by wenjunhj** [korvin011/ADS-Matlab-Interface#8]
Hi Korvin, 

I have an issue with this interface. When I try to run Demo 2, I get this message: 

> [ADS][20:11:41] Running ADS simulator "hpeesofsim"...
> HPEESOF_DIR is set to an invalid directory.  _""C:\Program Files\Keysight\ADS2020"\bin" does not exist_.
> Error setting up command line: HPEESOF_DIR is set to an invalid directory.  _""C:\Program Files\Keysight\ADS2020"\bin" does not exist_. 
> hpeesofsim (*) 510.shp Jul 22 2019, MINT version 5 
>     (64-bit windows built: Mon Jul 22, 2019 22:53:59 +0000) 
>  
>  
> ***** Warning: Unable to locate environment value for AEL_PATH ***** 
> 	Using default value of "." 
>  
> ***** Warning: Unable to locate environment value for HPEESOFSIM_AEL ***** 
> 	Using default value of "hpeesofsim" 
> WARNING    AEL0056 hpeesofsim: AEL file not found 
> *** FATAL ERROR: Unable to load default AEL personality *** 

I get the same message when I manually run in MATLAB console `[status, cmdout] = system('hpeesofsim "netlist.log"')` or `[status, cmdout] = system('hpeesofsim netlist.log')`.
I have set all environment variables manually in Control Panel > System > Advanced system settings > Environment variables, including `HPEESOF_DIR`, `COMPL_DIR`. I have also called 
```
ADSInstallationDir = 'C:\Program Files\Keysight\ADS2020\';
ADS.SetADSPaths(ADSInstallationDir);
```
before calling `ADS.RunSimulation('Verbosity', 'all'). `

I am using MATLAB R2019a and ADS 2020. However, I don't think the ADS version constitutes the problem; when I run the command `hpeesofsim "netlist.log"` in Windows cmd, everything goes fine. The project has no problem getting opened by ADS 2020 or simulated by clicking the simulation icon. 

> hpeesofsim (*) 510.shp Jul 22 2019, MINT version 5
>     (64-bit windows built: Mon Jul 22, 2019 22:53:59 +0000)
> 
> Parsing the netlist ...
> Flattening the netlist ...
> 
> AC AC1[1] <netlist.log>   freq=3 GHz
> 
> Evaluating unattached measurement equations ...
> Flushing unattached measurement equation results ...
> Checking for unresolved variables ...
> Flushing data (please wait) ...
> Flushing unattached measurement equation results ...
>      ... data flush done.
> 
> Resource usage:
>   Total stopwatch time     =     0.95 seconds.
> 

What do you think might be the reason? Thank you.

Best regards, 
Wenjun

**Comment by korvin011** [comment]
Hi,

I believe I had once similar issue... HPEESOF_DIR has extra `"` in the path. Try to remove last back slash from `ADSInstallationDir = 'C:\Program Files\Keysight\ADS2020\';`, i.e. `ADSInstallationDir = 'C:\Program Files\Keysight\ADS2020';`
If it helps, I will fix it later.

BR,
Oleg

**Comment by wenjunhj** [comment]
Hi Oleg, 

I believe it is lines 1,449 - 1,452 in `TADSInterface.m` that make trouble: 
```
 % if value contains spaces, we assume it is a path, and surround it with " 
 if any(EnvVarValue==' ')
    EnvVarValue = ['"' EnvVarValue '"']; %#ok<AGROW>
 end
```
It automatically adds double quote marks beside the directory's name `C:\Program Files\Keysight\ADS2020`.
Once I comment these lines, and call 
```
ADSInstallationDir = 'C:\Program Files\Keysight\ADS2020';
ADS.SetADSPaths(ADSInstallationDir, false);
```
the problem goes away. Please consider fixing this. 

Best regards, 
Wenjun
